version: 'minty.abcxyz.dev/v2'

rule:
  if: |-
    assertion.iss == 'https://token.actions.githubusercontent.com' &&
    assertion.organization_id == '93787867' &&
    assertion.repository_id == '575621363' &&
    assertion.ref == 'refs/heads/main'

scope:
  create-tag:
    rule:
      if: |-
        assertion.workflow_ref.startsWith("abcxyz/pmap/.github/workflows/create-tag.yml") &&
        assertion.workflow_ref == assertion.job_workflow_ref &&
        assertion.event_name == 'workflow_dispatch'
    repositories:
      - 'pmap'
    permissions:
      contents: 'write'

  draft-release:
    rule:
      if: |-
        assertion.workflow_ref.startsWith("abcxyz/pmap/.github/workflows/draft-release.yml") &&
        assertion.workflow_ref == assertion.job_workflow_ref &&
        assertion.event_name == 'workflow_dispatch'
    repositories:
      - 'pmap'
    permissions:
      contents: 'write'
      pull_requests: 'write'

  release:
    rule:
      if: |-
        assertion.workflow_ref.startsWith("abcxyz/pmap/.github/workflows/release.yml") &&
        assertion.workflow_ref == assertion.job_workflow_ref &&
        assertion.event_name == 'workflow_dispatch'
    repositories:
      - 'pmap'
    permissions:
      contents: 'write'

