# Copyright 2023 The Authors (see AUTHORS file)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This goreleaser yaml file is dedicated for ci workflows
# and is identical to goreleaser.docker.ci.yaml.
# The only difference is this only releases with OS=linux and Arch=amd64
# for releasing images for arm architectures so we can have a faster
# CI workflow run.
# When doing a actual release, please use the release workflow or
# goreleaser.docker.yaml.
env:
  # Global env vars for Go build.
  - 'CGO_ENABLED=0'
  - 'GO111MODULE=on'
  - 'GOPROXY=https://proxy.golang.org,direct'

before:
  hooks:
    - 'go mod tidy'

builds:
  -
    id: 'pmap'
    main: './cmd/pmap'
    binary: 'pmap'
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - '-a'
      - '-trimpath'
    ldflags:
      - '-s'
      - '-w'
      - '-X={{ .ModulePath }}/internal/version.Name=pmap'
      - '-X={{ .ModulePath }}/internal/version.Version={{ .Version }}'
      - '-X={{ .ModulePath }}/internal/version.Commit={{ .Commit }}'
      - '-extldflags=-static'
    goos:
      - 'linux'
    goarch:
      - 'amd64'

  -
    id: 'pmap-prober'
    main: './prober'
    binary: 'pmap-prober'
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - '-a'
      - '-trimpath'
    ldflags:
      - '-s'
      - '-w'
      - '-X={{ .ModulePath }}/internal/version.Name=pmap-prober'
      - '-X={{ .ModulePath }}/internal/version.Version={{ .Version }}'
      - '-X={{ .ModulePath }}/internal/version.Commit={{ .Commit }}'
      - '-extldflags=-static'
    goos:
      - 'linux'
    goarch:
      - 'amd64'

dockers:
  -
    ids:
      - 'pmap'
    use: 'buildx'
    goos: 'linux'
    goarch: 'amd64'
    image_templates:
      - '{{ .Env.DOCKER_REPO }}/pmap:{{ if index .Env "DOCKER_TAG"  }}{{ .Env.DOCKER_TAG }}{{ else }}{{ .Version }}{{ end }}-amd64'
    build_flag_templates:
      - '--platform=linux/amd64'
      - '--pull'
      - '--label=org.opencontainers.image.created={{ .CommitTimestamp }}'
      - '--label=org.opencontainers.image.description=Privacy data mapping tool'
      - '--label=org.opencontainers.image.licenses=Apache-2.0'
      - '--label=org.opencontainers.image.name=pmap'
      - '--label=org.opencontainers.image.revision={{ .FullCommit }}'
      - '--label=org.opencontainers.image.source={{ .GitURL }}'
      - '--label=org.opencontainers.image.title=pmap'
      - '--label=org.opencontainers.image.version={{ .Version }}'

  -
    ids:
      - 'pmap-prober'
    use: 'buildx'
    goos: 'linux'
    goarch: 'amd64'
    image_templates:
      - '{{ .Env.DOCKER_REPO }}/pmap-prober:{{ if index .Env "DOCKER_TAG"  }}{{ .Env.DOCKER_TAG }}{{ else }}{{ .Version }}{{ end }}-amd64'
    dockerfile: './prober/prober.dockerfile'
    build_flag_templates:
      - '--platform=linux/amd64'
      - '--pull'
      - '--label=org.opencontainers.image.created={{ .CommitTimestamp }}'
      - '--label=org.opencontainers.image.description=Prober for pmap'
      - '--label=org.opencontainers.image.licenses=Apache-2.0'
      - '--label=org.opencontainers.image.name=pmap-prober'
      - '--label=org.opencontainers.image.revision={{ .FullCommit }}'
      - '--label=org.opencontainers.image.source={{ .GitURL }}'
      - '--label=org.opencontainers.image.title=pmap-prober'
      - '--label=org.opencontainers.image.version={{ .Version }}'

docker_manifests:
  -
    name_template: '{{ .Env.DOCKER_REPO }}/pmap:{{ if index .Env "DOCKER_TAG"  }}{{ .Env.DOCKER_TAG }}{{ else }}{{ .Version }}{{ end }}'
    image_templates:
      - '{{ .Env.DOCKER_REPO }}/pmap:{{ if index .Env "DOCKER_TAG"  }}{{ .Env.DOCKER_TAG }}{{ else }}{{ .Version }}{{ end }}-amd64'

  -
    name_template: '{{ .Env.DOCKER_REPO }}/pmap-prober:{{ if index .Env "DOCKER_TAG"  }}{{ .Env.DOCKER_TAG }}{{ else }}{{ .Version }}{{ end }}'
    image_templates:
      - '{{ .Env.DOCKER_REPO }}/pmap-prober:{{ if index .Env "DOCKER_TAG"  }}{{ .Env.DOCKER_TAG }}{{ else }}{{ .Version }}{{ end }}-amd64'

# TODO: Follow up on signing.

# Disable SCM release we only want docker release here.
release:
  disable: true
