name: 'pmap-resource-mapping-check'
on:
  workflow_call:
    inputs:
      resource_mapping_directory:
        description: 'The directory which includes the resource mapping yaml and yml files'
        type: 'string'
        required: true
      go_version:
        description: 'The version of Golang'
        type: 'string'
        required: true
jobs:
  check:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3' # ratchet:actions/checkout@v3
        with:
          fetch-depth: 0 # OR "2" -> To retrieve the preceding commit.
      - name: 'Get changed yaml and yml files'
        id: 'changed-yaml-files'
        uses: 'tj-actions/changed-files@b109d83a62e94cf7c522bf6c15cb25c175850b16' # ratchet:tj-actions/changed-files@v35
        with:
          files: |
            ${{ inputs.resource_mapping_directory }}/**/*.{yaml,yml}
          files_ignore: |
            **/.github/workflows/**/*.{yaml, yml}
      - name: 'Copy added and changed files'
        if: ${{ steps.changed-yaml-files.outputs.any_changed == 'true' }}
        run: |
          echo ${{ env.RUNNER_TEMP }}
          sudo mkdir -p ${{ env.RUNNER_TEMP }}/pmap/snapshot-file-change
          for file in ${{ steps.changed-yaml-files.outputs.added_files }}; do
            echo "$file was added"
            sudo cp --parents $file ${{ env.RUNNER_TEMP }}/pmap/snapshot-file-change
            echo "$file was copied to ${{ env.RUNNER_TEMP }}/pmap/snapshot-file-change"
          done
          for file in ${{ steps.changed-yaml-files.outputs.modified_files }}; do
            echo "$file was modified"
            sudo cp --parents $file ${{ env.RUNNER_TEMP }}/pmap/snapshot-file-change
            echo "$file was copied to ${{ env.RUNNER_TEMP }}/pmap/snapshot-file-change"
          done
      - id: 'setup-go'
        uses: 'actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568' # ratchet:actions/setup-go@v3
        with:
          go-version: ${{ inputs.go_version }}
      - id: 'install-pmapctl'
        shell: 'bash'
        run: 'go install github.com/abcxyz/pmap/cmd/pmap@latest'
      - id: 'run-check'
        shell: 'bash'
        run: 'pmap validate -type ResourceMapping -path ${{ env.RUNNER_TEMP }}/pmap/snapshot-file-change'
