name: 'ci'

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:
  workflow_call:

concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.ref }}-ci'
  cancel-in-progress: true

jobs:
  # Linting jobs - terraform, java, go
  terraform_lint:
    uses: 'abcxyz/pkg/.github/workflows/terraform-lint.yml@cc2b918b16df0f627b933ed8dddf0d846fa9108b' # ratchet:abcxyz/pkg/.github/workflows/terraform-lint.yml@main
    with:
      directory: 'terraform'
      terraform_version: '1.2'

  go_lint:
    uses: 'abcxyz/pkg/.github/workflows/go-lint.yml@main'
    with:
      go_version: '1.19'

  java_lint:
    uses: 'abcxyz/pkg/.github/workflows/java-lint.yml@cc2b918b16df0f627b933ed8dddf0d846fa9108b' # ratchet:abcxyz/pkg/.github/workflows/java-lint.yml@main
    with:
      directory: 'clients/java-logger'
      java_version: '11'

  # Unit tests - java, go
  go_test:
    uses: 'abcxyz/pkg/.github/workflows/go-test.yml@cc2b918b16df0f627b933ed8dddf0d846fa9108b' # ratchet:abcxyz/pkg/.github/workflows/go-test.yml@main
    with:
      go_version: '1.19'
      go_packages: |-
        $(go list ./... | grep -v -E 'pmap/third_party|pamp/integration')

  # lint_and_unit is a virtual job that is used as dependencies for later jobs.
  lint_and_unit:
    runs-on: 'ubuntu-latest'
    needs:
      - 'terraform_lint'
      - 'go_lint'
      - 'java_lint'
      - 'go_test'
    steps:
      - run: 'echo prechecks complete'
        