name: 'ci'

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  # Linting jobs - go, terraform.
  go_lint:
    uses: 'abcxyz/pkg/.github/workflows/go-lint.yml@main' # ratchet:exclude
    with:
      go_version: '1.19'

  terraform_lint:
    uses: 'abcxyz/pkg/.github/workflows/terraform-lint.yml@05893fce7fae208eb14b8952caf0a20acfdc772c' # ratchet:abcxyz/pkg/.github/workflows/terraform-lint.yml@main
    with:
      directory: 'terraform'
      terraform_version: '1.3'

  # lint is a virtual job that is used as dependencies for later jobs.
  lint:
    runs-on: 'ubuntu-latest'
    needs:
      - 'go_lint'
    steps:
      - run: 'echo prechecks complete'
