name: 'fake-bets-mapping-snapshot-file-change'

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

# Don't cancel in progress since we don't want to have half-baked file change snapshot.
concurrency: '${{ github.workflow }}-${{ github.head_ref || github.ref }}-fake-bets-mapping-snapshot-file-change'

jobs:
  snapshot:
    uses: './.github/workflows/file-change.yml' # ratchet:exclude
    with:
      workload_identity_provider: 'projects/921163060412/locations/global/workloadIdentityPools/github-pool-3b39/providers/github-provider'
      service_account: 'pmap-3b39-ci-sa@pmap-ci.iam.gserviceaccount.com'
      destination_prefix: 'pmap-dev/mapping'
      path: 'test/e2e/testdata/fakebets/mapping'
