name: 'pmap-resource-mapping-check'
on:
  workflow_call:
    inputs:
      resource_mapping_directory:
        description: 'The directory which includes the resource mapping yaml files'
        type: 'string'
        required: true
      go_version:
        description: 'The version of Golang'
        type: 'string'
        required: true
      pmap_version:
        description: 'The version of pmap command line'
        type: 'string'
        default: 'latest'
jobs:
  check:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9' # ratchet:actions/checkout@v3
        with:
          fetch-depth: 0 # OR "2" -> To retrieve the preceding commit.
      - name: 'Get changed yaml files'
        id: 'changed-yaml-files'
        uses: 'tj-actions/changed-files@fb20f4d24890fadc539505b1746d260504b213d0' # ratchet:tj-actions/changed-files@v36
        with:
          files: |
            ${{ inputs.resource_mapping_directory }}/**/*.{yaml,yml}
      - name: 'Copy added and changed files'
        if: '${{ steps.changed-yaml-files.outputs.any_changed == ''true'' }}'
        run: |
          echo ${{ env.RUNNER_TEMP }}
          sudo mkdir -p ${{ env.RUNNER_TEMP }}/pmap/snapshot-file-change
          for file in ${{ steps.changed-yaml-files.outputs.added_files }}; do
            echo "$file was added"
            sudo cp --parents $file ${{ env.RUNNER_TEMP }}/pmap/snapshot-file-change
            echo "$file was copied to ${{ env.RUNNER_TEMP }}/pmap/snapshot-file-change"
          done
          for file in ${{ steps.changed-yaml-files.outputs.modified_files }}; do
            echo "$file was modified"
            sudo cp --parents $file ${{ env.RUNNER_TEMP }}/pmap/snapshot-file-change
            echo "$file was copied to ${{ env.RUNNER_TEMP }}/pmap/snapshot-file-change"
          done
      - id: 'setup-go'
        uses: 'actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568' # ratchet:actions/setup-go@v3
        with:
          go-version: '${{ inputs.go_version }}'
      - id: 'run-check'
        if: '${{ steps.changed-yaml-files.outputs.any_changed == ''true'' }}'
        shell: 'bash'
        run: |-
          go install github.com/abcxyz/pmap/cmd/pmap@${{ inputs.pmap_version }}
          pmap mapping validate -path ${{ env.RUNNER_TEMP }}/pmap/snapshot-file-change
