name: 'pmap-snapshot-file-copy'
on:
  workflow_call:
    inputs:
      workload_identity_provider:
        description: 'The full identifier of the Workload Identity Provider, including the project number, pool name, and provider name.'
        type: 'string'
        required: true
      service_account:
        description: 'Email address or unique identifier of the Google Cloud service account for which to generate credentials.'
        type: 'string'
        required: true
      destination_prefix:
        description: 'The destination prefix for the file/folder in the form bucket-name or with an optional prefix in the form bucket-name/prefix.'
        type: 'string'
        required: true
      path:
        description: 'The path to a file or folder in the GitHub repo that should be uploaded to the gcs.'
        type: 'string'
        required: true
jobs:
  snapshot:
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'read'
      id-token: 'write'
    name: 'Snapshot changed files'
    steps:
      - uses: 'actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9' # ratchet:actions/checkout@v3
        with:
          fetch-depth: 0 # OR "2" -> To retrieve the preceding commit.
      - name: 'Authenticate to Google Cloud'
        id: 'auth'
        uses: 'google-github-actions/auth@35b0e87d162680511bf346c299f71c9c5c379033' # ratchet:google-github-actions/auth@v1
        with:
          workload_identity_provider: '${{ inputs.workload_identity_provider }}'
          service_account: '${{ inputs.service_account }}'
      # set timestamp with format: 2023-05-23T03:38:33+00:00
      - name: 'Set current timestamp'
        run: |
          echo "CUR_TIMESTAMP=$(date --rfc-3339=seconds | sed 's/ /T/')" >> $GITHUB_ENV
      - name: 'GCS upload files'
        id: 'gcs-upload-file'
        uses: 'google-github-actions/upload-cloud-storage@e95a15f226403ed658d3e65f40205649f342ba2c' # ratchet:google-github-actions/upload-cloud-storage@v1
        if: '${{ hashFiles(''./${{ inputs.path}} /*'') != '''' }}'
        with:
          path: '${{ inputs.path }}'
          # we use gh-prefix as the separator so we can retrive each file's original path after it's uploaded to GCS.
          destination: '${{ inputs.destination_prefix }}/copy-${{ github.run_id }}-${{ github.run_attempt }}/gh-prefix/${{ inputs.path }}'
          parent: false
          glob: |
            **/*.{yml,yaml}
          headers: |-
            content-type: application/json
            x-goog-meta-github-commit: ${{ github.sha }}
            x-goog-meta-github-repo: ${{ github.repository }}
            x-goog-meta-github-run-attempt: ${{github.run_attempt}}
            x-goog-meta-github-run-id: ${{github.run_id}}
            x-goog-meta-github-workflow: ${{ github.workflow }}
            x-goog-meta-github-workflow-sha: ${{ github.workflow_sha }}
            x-goog-meta-github-workflow-triggered-timestamp: ${{ env.CUR_TIMESTAMP }}
      - name: 'List all uploaded files'
        run: |-
          echo "all gcs uploaded files"
          echo '${{ steps.gcs-upload-file.outputs.uploaded }}'
