name: 'pmap-snapshot-file-change'
on:
  workflow_call:
    inputs:
      workload_identity_provider:
        description: 'The full identifier of the Workload Identity Provider, including the project number, pool name, and provider name.'
        type: 'string'
        required: true
      service_account:
        description: 'Email address or unique identifier of the Google Cloud service account for which to generate credentials.'
        type: 'string'
        required: true
      destination_prefix:
        description: 'The destination prefix for the file/folder in the form bucket-name or with an optional prefix in the form bucket-name/prefix.'
        type: 'string'
        required: true
      path:
        description: 'The path to a file or folder in the GitHub repo that should be uploaded to the gcs.'
        type: 'string'
        required: true

jobs:
  snapshot:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    name: 'Snapshot changed files'
    steps:
      - uses: 'actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c' # ratchet:actions/checkout@v3
        with:
          fetch-depth: 0 # OR "2" -> To retrieve the preceding commit.
      - name: 'Set current timestamp'
        run: |
          echo "CUR_TIMESTAMP=$(date --rfc-3339=seconds | sed 's/ /T/')" >> $GITHUB_ENV
      - name: 'Get changed yaml files'
        id: 'changed-yaml-files'
        uses: 'tj-actions/changed-files@84ed30e2f4daf616144de7e0c1db59d5b33025e3' # ratchet:tj-actions/changed-files@v35
        with:
          files: |
            ${{ inputs.path }}/**/*.{yml,yaml}
      - name: 'Copy added and changed files'
        id: 'copy-changed-yaml-files'
        if: ${{ steps.changed-yaml-files.outputs.any_changed == 'true' }}
        run: |
          echo ${{ env.RUNNER_TEMP }}
          sudo mkdir -p ${{ env.RUNNER_TEMP }}/pmap/snapshot-file-change
          for file in ${{ steps.changed-yaml-files.outputs.added_files }}; do
            echo "$file was added"
            sudo cp --parents $file ${{ env.RUNNER_TEMP }}/pmap/snapshot-file-change
            echo "$file was copied to ${{ env.RUNNER_TEMP }}/pmap/snapshot-file-change"
          done
          for file in ${{ steps.changed-yaml-files.outputs.modified_files }}; do
            echo "$file was modified"
            sudo cp --parents $file ${{ env.RUNNER_TEMP }}/pmap/snapshot-file-change
            echo "$file was copied to ${{ env.RUNNER_TEMP }}/pmap/snapshot-file-change"
          done
      - name: 'Authenticate to Google Cloud'
        id: 'auth'
        uses: 'google-github-actions/auth@ef5d53e30bbcd8d0836f4288f5e50ff3e086997d' # ratchet:google-github-actions/auth@v1
        with:
          workload_identity_provider: '${{ inputs.workload_identity_provider }}'
          service_account: '${{ inputs.service_account }}'
      - name: 'GCS upload files'
        if: ${{ steps.copy-changed-yaml-files.outcome == 'success' }}
        id: 'gcs-upload-file'
        uses: 'google-github-actions/upload-cloud-storage@a5b77a3bf84da1791719585d327e5f90ae5cb53c' # ratchet:google-github-actions/upload-cloud-storage@v1
        with:
          path: '${{ env.RUNNER_TEMP }}/pmap/snapshot-file-change'
          parent: false
          destination: '${{ inputs.destination_prefix }}/pmap-file-change-${{ github.run_id }}-${{ github.run_attempt }}'
          headers: |-
            content-type: application/json
            x-goog-meta-github-commit: ${{ github.sha }}
            x-goog-meta-github-repo: ${{ github.repository }}
            x-goog-meta-github-run-attempt: ${{github.run_attempt}}
            x-goog-meta-github-run-id: ${{github.run_id}}
            x-goog-meta-github-workflow: ${{ github.workflow }}
            x-goog-meta-github-workflow-sha: ${{ github.workflow_sha }}
            x-goog-meta-github-workflow-triggered-timestamp: ${{ env.CUR_TIMESTAMP }}
      - name: 'List all uploaded files'
        run: |-
          echo "all gcs uploaded files"
          echo '${{ steps.gcs-upload-file.outputs.uploaded }}'
