# Copyright 2023 The Authors (see AUTHORS file)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: 'pmap-snapshot-file-change'
on:
  workflow_call:
    inputs:
      workload_identity_provider:
        description: 'The full identifier of the Workload Identity Provider, including the project number, pool name, and provider name.'
        type: 'string'
        required: true
      service_account:
        description: 'Email address or unique identifier of the Google Cloud service account for which to generate credentials.'
        type: 'string'
        required: true
      destination_prefix:
        description: 'The destination prefix for the file/folder in the form bucket-name or with an optional prefix in the form bucket-name/prefix.'
        type: 'string'
        required: true
      path:
        description: 'The path to a file or folder in the GitHub repo that should be uploaded to the gcs.'
        type: 'string'
        required: true
jobs:
  snapshot:
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'read'
      id-token: 'write'
    name: 'Snapshot changed files'
    steps:
      - uses: 'actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683' # ratchet:actions/checkout@v4
        with:
          fetch-depth: 0 # OR "2" -> To retrieve the preceding commit.
      # set timestamp with format: 2023-05-23T03:38:33+00:00
      - name: 'Set current timestamp'
        run: |
          echo "CUR_TIMESTAMP=$(date --rfc-3339=seconds | sed 's/ /T/')" >> "${GITHUB_ENV}"

      - name: 'Get changed yaml files'
        id: 'changed-yaml-files'
        uses: 'step-security/changed-files@3dbe17c78367e7d60f00d78ae6781a35be47b4a1' # ratchet:step-security/changed-files@v45
        with:
          files: |
            ${{ inputs.path }}/**/*.{yml,yaml}

      - name: 'Copy added and changed files'
        id: 'copy-changed-yaml-files'
        if: '${{ steps.changed-yaml-files.outputs.any_changed == ''true'' }}'
        run: |
          echo ${{ env.RUNNER_TEMP }}
          sudo mkdir -p ${{ env.RUNNER_TEMP }}/pmap/snapshot-file-change
          for file in ${{ steps.changed-yaml-files.outputs.added_files }}; do
            echo "$file was added"
            sudo cp --parents $file ${{ env.RUNNER_TEMP }}/pmap/snapshot-file-change
            echo "$file was copied to ${{ env.RUNNER_TEMP }}/pmap/snapshot-file-change"
          done
          for file in ${{ steps.changed-yaml-files.outputs.modified_files }}; do
            echo "$file was modified"
            sudo cp --parents $file ${{ env.RUNNER_TEMP }}/pmap/snapshot-file-change
            echo "$file was copied to ${{ env.RUNNER_TEMP }}/pmap/snapshot-file-change"
          done

      - name: 'Authenticate to Google Cloud'
        id: 'auth'
        uses: 'google-github-actions/auth@6fc4af4b145ae7821d527454aa9bd537d1f2dc5f' # ratchet:google-github-actions/auth@v2
        with:
          workload_identity_provider: '${{ inputs.workload_identity_provider }}'
          service_account: '${{ inputs.service_account }}'

      - name: 'GCS upload files'
        if: '${{ steps.copy-changed-yaml-files.outcome == ''success'' }}'
        id: 'gcs-upload-file'
        uses: 'google-github-actions/upload-cloud-storage@386ab77f37fdf51c0e38b3d229fad286861cc0d0' # ratchet:google-github-actions/upload-cloud-storage@v2
        with:
          path: '${{ env.RUNNER_TEMP }}/pmap/snapshot-file-change'
          parent: false
          # we use gh-prefix as the separator so we can retrive each file's original path after it's uploaded to GCS.
          destination: '${{ inputs.destination_prefix }}/change-${{ github.run_id }}-${{ github.run_attempt }}/gh-prefix'
          headers: |-
            content-type: application/json
            x-goog-meta-github-commit: ${{ github.sha }}
            x-goog-meta-github-repo: ${{ github.repository }}
            x-goog-meta-github-run-attempt: ${{github.run_attempt}}
            x-goog-meta-github-run-id: ${{github.run_id}}
            x-goog-meta-github-workflow: ${{ github.workflow }}
            x-goog-meta-github-workflow-sha: ${{ github.workflow_sha }}
            x-goog-meta-github-workflow-triggered-timestamp: ${{ env.CUR_TIMESTAMP }}

      - name: 'List all uploaded files'
        run: |-
          echo "all gcs uploaded files"
          echo '${{ steps.gcs-upload-file.outputs.uploaded }}'
